services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      DATABASE_PATH: /data/database.sqlite
      WHATSAPP_SERVICE_URL: http://whatsapp-service:8080
      INSTAGRAM_SERVICE_URL: http://instagram-service:8090
    volumes:
      - ./database:/data
    depends_on:
      - whatsapp-service
      - instagram-service
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000
    ports:
      - "3001:80"
    depends_on:
      - api
    restart: unless-stopped

  # Microservice WhatsApp (Go)
  whatsapp-service:
    build:
      context: ./Whatsapp-service
    ports:
      - "8080:8080"
    volumes:
      - ./Whatsapp-service:/app
    restart: unless-stopped

  instagram-service:
    build:
      context: ./instagramApi
    ports:
      - "8090:8090"
    volumes:
      - ./instagramApi:/app
    restart: unless-stopped
